version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pismo
    ports:
      - "3307:3306"
    volumes:
      - /home/Docker/Volumes/mysql/var/lib/mysql/data
      